var hierarchy =
[
    [ "CoffinCageMinigameTest", "class_coffin_cage_minigame_test.html", null ],
    [ "DialogueTest", "class_dialogue_test.html", null ],
    [ "GraveInteractionTest", "class_grave_interaction_test.html", null ],
    [ "ImageLoader", "class_image_loader.html", null ],
    [ "Line", "class_line.html", null ],
    [ "MonoBehaviour", null, [
      [ "Beacon", "class_beacon.html", null ],
      [ "BodyGeneration", "class_body_generation.html", null ],
      [ "Bush", "class_bush.html", null ],
      [ "CoffinCageMiniGame", "class_coffin_cage_mini_game.html", null ],
      [ "Dialogue", "class_dialogue.html", null ],
      [ "DigSliderControl", "class_dig_slider_control.html", null ],
      [ "DistanceCamMove", "class_distance_cam_move.html", null ],
      [ "DontDestroyOnLoad", "class_dont_destroy_on_load.html", null ],
      [ "FenceTile", "class_fence_tile.html", null ],
      [ "GameManager", "class_game_manager.html", null ],
      [ "GenerateHeadStone", "class_generate_head_stone.html", null ],
      [ "GraveInfo", "class_grave_info.html", null ],
      [ "GraveInteraction", "class_grave_interaction.html", null ],
      [ "Guard", "class_guard.html", null ],
      [ "MapGeneration", "class_map_generation.html", null ],
      [ "PathTile", "class_path_tile.html", null ],
      [ "Player", "class_player.html", null ],
      [ "PlayerFlipManager", "class_player_flip_manager.html", null ],
      [ "QuestManager", "class_quest_manager.html", null ],
      [ "SceneController", "class_scene_controller.html", null ],
      [ "SoundManager", "class_sound_manager.html", null ],
      [ "StealthManager", "class_stealth_manager.html", null ],
      [ "TestNewButton", "class_test_new_button.html", null ],
      [ "TileData", "class_tile_data.html", null ],
      [ "TorpedoMinigame", "class_torpedo_minigame.html", null ],
      [ "Tree", "class_tree.html", null ],
      [ "TripWireMiniGame", "class_trip_wire_mini_game.html", null ],
      [ "TripWireMiniGameTrigger", "class_trip_wire_mini_game_trigger.html", null ]
    ] ],
    [ "QuestManagerTest", "class_quest_manager_test.html", null ],
    [ "ScriptableObject", null, [
      [ "Quests", "class_quests.html", null ],
      [ "Script", "class_script.html", null ]
    ] ],
    [ "StealthTest", "class_stealth_test.html", null ],
    [ "TerrainTest", "class_terrain_test.html", null ],
    [ "TorpedoMiniGameTests", "class_torpedo_mini_game_tests.html", null ],
    [ "TripWireMiniGameTest", "class_trip_wire_mini_game_test.html", null ]
];